languageCode: en
theme: osuny-hugo-theme
languages:
  en:
    title: Degrowth journal
paginate: 18
permalinks:
  pages:          /pages/:slug/
  articles:       /articles/:slug/
  persons:        /authors/:slug/
  researchers:    /authors/:slug/publications
taxonomies:
  researcher:     researchers
  volume:         volumes
