params:
  cookie_banner:
    enable: false
baseURL: /
languageCode: en
languages:
  en:
    title: Degrowth journal
theme: osuny-hugo-theme
paginate: 18
permalinks:
  pages:          /pages/:slug/
  articles:       /articles/:slug/
  persons:        /authors/:slug/
  researchers:    /authors/:slug/publications
taxonomies:
  researcher:     researchers
  volume:         volumes
