title: Clermont Auvergne journal degrowth
languageCode: en
theme: hugo-osuny
paginate: 18
permalinks:
  pages:          /pages/:slug/
  authors:        /authors/:slug
  articles:       /articles/:slug
  volumes:        /volumes/:slug
