languageCode: en
theme: osuny-hugo-theme
languages:
  en:
    title: Degrowth journal
paginate: 18
permalinks:
  pages:          /pages/:slug/
  authors:        /authors/:slug/
  articles:       /articles/:slug/
  researchers:    /researchers/:slug/
taxonomies:
  administrator:  administrators
  author:         authors
  category:       categories
  researcher:     researchers
  teacher:        teachers
  volume:         volumes
